robot_base_frame: base_footprint
transform_tolerance: 0.4
update_frequency: 10.0
publish_frequency: 5.0
obstacle_range: 1.0
publish_voxel_map: false
meter_scoring: true

obstacles:
  observation_sources: front_scan_sensor
  front_scan_sensor: {
    topic: scan,
    sensor_frame: lidar_link,
    observation_persistence: 0.0,
    expected_update_rate: 0.5,
    data_type: LaserScan,
    clearing: true,
    marking: true,
    max_obstacle_height: 1.0,
    min_obstacle_height: 0.0,
    obstacle_range: 1.5,
    raytrace_range: 2.0
  }